### ISSUE TITLE
DatasourceProxyBeanPostProcessor logging messages twice

### ISSUE THREAD

**Issue by nbabb** [ttddyy/datasource-proxy-examples#15]
Hello, I'm using `DatasourceProxyBeanPostProcessor` from the example, in a spring boot application (2.1.4).  The bean coming into the proxy is type `com.zaxxer.hikari.HikariDataSource$$EnhancerBySpringCGLIB$$3d556de0`.  What I'm seeing is that, with show-sql turned on, hibernate displays one query as having been executed, but the proxy datasource is logging two messages.   The ProxyDataSourceInterceptor.invoke method is called twice as well.  When I put a breakpoint in `4JQueryLoggingListener.writeLog` I get the attached stacktraces.  My goal is to be able to accurately count select queries.  I would expect one query but the `QueryCount` is showing two (see attached).  Any help is appreciated. 

[first_log_write.txt](https://github.com/ttddyy/datasource-proxy-examples/files/3381767/first_log_write.txt)
[second_log_write.txt](https://github.com/ttddyy/datasource-proxy-examples/files/3381768/second_log_write.txt)

**Comment by ttddyy** [comment]
According to `first_log_write.txt`, it stlil seems the datasource is proxied twice.

```
...
performQueryExecutionListener:395, StatementProxyLogic {net.ttddyy.dsproxy.proxy}
...
performQueryExecutionListener:316, StatementProxyLogic {net.ttddyy.dsproxy.proxy}
...
```

Can you check the `DatasourceProxyBeanPostProcessor` and make sure it is only making a proxy once.

**Comment by nbabb** [comment]
So logging revealed that the postProcessAfterInitialization was being called twice (my breakpoint was only being hit once).

First Log message
Instantiating ProxyDataSourceInterceptor class com.zaxxer.hikari.HikariDataSource$$EnhancerBySpringCGLIB$$c14cde91

Second Log message
Instantiating ProxyDataSourceInterceptor class com.zaxxer.hikari.HikariDataSource

I changed the code to 

```
    private ProxyFactory factory;
    @Override
    public Object postProcessAfterInitialization(Object bean, String beanName) {
        if (bean instanceof DataSource && factory == null) {
```
and that seems to fix the issue, though not sure this is the best solution.  In the javadoc for postProcessAfterInitialization I see this comment

`In case of a FactoryBean, this callback will be invoked for both the FactoryBean
	 * instance and the objects created by the FactoryBean (as of Spring 2.0)`

**Comment by ttddyy** [comment]
So, according to the javadoc of `BeanPostProcessor#postProcessAfterInitialization`

> <p>In case of a FactoryBean, this callback will be invoked for both the FactoryBean
> instance and the objects created by the FactoryBean (as of Spring 2.0). The
> post-processor can decide whether to apply to either the FactoryBean or created
> objects or both through corresponding {@code bean instanceof FactoryBean} checks.

This means, adding `!(bean instanceof FactoryBean)` to the condition sounds like an answer to me.

```java
@Override
public Object postProcessAfterInitialization(Object bean, String beanName) {
  if (bean instanceof DataSource && !(bean instanceof ProxyDataSource) && !(bean instanceof FactoryBean)) {
    ...
  }
}
```

**Comment by nbabb** [comment]
Yes, that seems like a better solution.  Seems this issue can be considered closed, from my perspective.  Thanks for checking on this.

**Comment by ttddyy** [comment]
Cool, glad it's been solved.
Closing the issue.
