### ISSUE TITLE
Reducie transaction Isolation level queries in ProxyDataSource with HikariCP and PostgreSQL

### ISSUE THREAD

**Issue by azemliankin** [ttddyy/datasource-proxy-examples#26]
### Prerequisites:

1. Spring Boot 3.1.0
2. HikariCP 5.0.1
3. PostgreSQL JDBC Driver 42.6.0
4. Datasource-proxy 1.9

### Setup:

```
ProxyDataSourceBuilder.create(ds) // ds is a HikariCP datasource 
                    .name(datasourceName)
                    .proxyResultSet()
                    .afterQuery(new JdbcQueryPostProcessor())
                    .build();
```

### Issue:
We use the Spring JDBC template to perform database queries through ProxyDataSource. For every single database query, the JdbcTemplate obtains a connection from ProxyDataSource. At this point, ProxyDataSource attempts to retrieve the transaction isolation level from the delegate datasource:

```
public class ProxyDataSource implements DataSource, Closeable {

    ...

    @Override
    public Connection getConnection() throws SQLException {
        final Connection conn = dataSource.getConnection();
        return getConnectionProxy(conn, GET_CONNECTION_WITH_NO_ARGS, null);
    }

    private Connection getConnectionProxy(final Connection conn, Method method, Object[] args) throws SQLException {
        String dataSourceName = this.proxyConfig.getDataSourceName();
        ConnectionIdManager connectionIdManager = this.proxyConfig.getConnectionIdManager();
        final JdbcProxyFactory jdbcProxyFactory = this.proxyConfig.getJdbcProxyFactory();

        String connectionId = connectionIdManager.getId(conn);

        final ConnectionInfo connectionInfo = new ConnectionInfo();
        connectionInfo.setConnectionId(connectionId);
        connectionInfo.setIsolationLevel(conn.getTransactionIsolation());   <-- MAKES EXTRA DB CALL
        connectionInfo.setDataSourceName(dataSourceName);

        ...

    }

}
```
The delegate datasource (which is HikariCP in our case) further delegates this to the PostgreSQL datasource. The PostgreSQL datasource then performs `execSQLQuery("SHOW TRANSACTION ISOLATION LEVEL")`. This results in an extra database call for every 'get connection from pool' operation.

Please consider adding a configuration property to disable the collection of the transaction isolation level. Alternatively, consider collecting it less frequently, as the isolation level is not something that is supposed to change often.

**Comment by rajadilipkolli** [comment]
Can you please move this issue to https://github.com/jdbc-observations/datasource-proxy as that is the main code base .

**Comment by ttddyy** [comment]
Thanks for handling it. It is reported to https://github.com/jdbc-observations/datasource-proxy/issues/109
