### ISSUE TITLE
Include how to use datasource-proxy  inside @DataJpaTest junit tests

### ISSUE THREAD

**Issue by rajadilipkolli** [ttddyy/datasource-proxy-examples#3]
I am using @DataJpaTest to test my database interactions , I want to use datasource-proxy to find what is being logged.

How to achieve this?

**Comment by ttddyy** [comment]
You need to wrap around your datasource.
Maybe inject the original datasource and return datasource-proxy wrapped datasource at `@Bean` method.

Please ask how to use `@DataJpaTest` at [spring-boot stackoverflow](https://stackoverflow.com/questions/tagged/spring-boot).

**Comment by rajadilipkolli** [comment]
For anyone looking at the solution see https://github.com/ttddyy/datasource-proxy-examples/tree/master/springboot-autoconfig-example and https://stackoverflow.com/a/44916344/5557885

**Comment by seguri** [comment]
@rajadilipkolli what's to be seen there? the example uses `@SpringBootTest` instead of `@DataJpaTest`, that alone is enough to get the desired logs.

Is there 6 years later a working example anywhere with `@DataJpaTest`?

**Comment by rajadilipkolli** [comment]
There is a working example written 6 years ago only @seguri , I have updated wrong link , thanks for pointing it out.

Here is the link

https://stackoverflow.com/a/44916344/5557885
